In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_excel('../data/fx_data.xlsx')

In [5]:
data.head()

,LON Fixes,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Date,AUDUSD CMPL Curncy (R1),USDCAD CMPL Curncy (L1),USDCHF CMPL Curncy (R3),NaN,EURUSD CMPL Curncy (R2),GBPUSD CMPL Curncy (L2),USDJPY CMPL Curncy (R1),USDNOK CMPL Curncy (L4),NZDUSD CMPL Curncy (R1),...,AUDUSD CMPN Curncy (L1),USDCAD CMPN Curncy (R2),USDCHF CMPN Curncy (L3),USDDKK CMPN Curncy (R4),EURUSD CMPN Curncy (L2),GBPUSD CMPN Curncy (R3),USDJPY CMPN Curncy (R1),USDNOK CMPN Curncy (R1),NZDUSD CMPN Curncy (R1),USDSEK CMPN Curncy (L4)
1,2023-11-15 00:00:00,0.6505,1.3699,0.8889,6.8700,1.0857,1.2461,150.4315,10.8578,0.6037,...,0.6506,1.3703,0.8889,6.8725,1.0853,1.2457,150.4655,10.8636,0.6035,10.5705
2,2023-11-14 00:00:00,0.6495,1.3714,0.8903,6.8603,1.0873,1.2493,150.6,10.8896,0.599,...,0.6507,1.3693,0.8891,6.8566,1.0879,1.2499,150.37,10.8821,0.6008,10.5921
3,2023-11-13 00:00:00,0.6384,1.3791,0.902,6.9738,1.0696,1.2268,151.64,11.075,0.5886,...,0.6377,1.3805,0.9016,6.9717,1.0698,1.2279,151.72,11.0849,0.5877,10.8429
4,2023-11-10 00:00:00,0.6357,1.381,0.9024,6.9832,1.0679,1.2217,151.56,11.1317,0.5888,...,0.6361,1.38,0.9027,6.9793,1.0686,1.2227,151.52,11.1132,0.5891,10.8965