In [5]:
import numpy as np
import pandas as pd

In [54]:
data = pd.read_excel('../data/fx_data.xlsx', header=[0,1], index_col=[0,1])
london_fix = pd.read_excel('../data/FX_Fixes.xlsx', sheet_name='LON_Fix', index_col=0, parse_dates=True)
ny_fix = pd.read_excel('../data/FX_Fixes.xlsx', sheet_name='NY_Fix', index_col=0, parse_dates=True)

In [55]:
london_fix.columns = [col.split()[0] for col in london_fix.columns]
ny_fix.columns = [col.split()[0] for col in ny_fix.columns]

,AUDUSD CMPN Curncy (L1),USDCAD CMPN Curncy (R2),USDCHF CMPN Curncy (L3),USDDKK CMPN Curncy (R4),EURUSD CMPN Curncy (L2),GBPUSD CMPN Curncy (R3),USDJPY CMPN Curncy (R1),USDNOK CMPN Curncy (R1),NZDUSD CMPN Curncy (R1),USDSEK CMPN Curncy (L4)
Date,,,,,,,,,,
2023-11-15,0.6506,1.3703,0.8889,6.8725,1.0853,1.2457,150.4655,10.8636,0.6035,10.5705
2023-11-14,0.6507,1.3693,0.8891,6.8566,1.0879,1.2499,150.3700,10.8821,0.6008,10.5921
2023-11-13,0.6377,1.3805,0.9016,6.9717,1.0698,1.2279,151.7200,11.0849,0.5877,10.8429
2023-11-10,0.6361,1.3800,0.9027,6.9793,1.0686,1.2227,151.5200,11.1132,0.5891,10.8965
2023-11-09,0.6367,1.3808,0.9029,6.9911,1.0668,1.2223,151.3500,11.2211,0.5894,10.9267
...,...,...,...,...,...,...,...,...,...,...
2000-01-07,0.6549,1.4558,1.5646,7.2257,1.0295,1.6393,105.3400,7.9748,0.5175,8.4167
2000-01-06,0.6533,1.4599,1.5532,7.2076,1.0328,1.6474,105.2300,7.9420,0.5146,8.3719
2000-01-05,0.6579,1.4500,1.5486,7.2118,1.0321,1.6426,104.1400,7.9430,0.5202,8.3671
2000-01-04,0.6550,1.4528,1.5573,7.2296,1.0296,1.6360,103.2200,7.9469,0.5194,8.3810
2000-01-03,0.6585,1.4468,1.5670,7.2640,1.0243,1.6362,101.4500,7.8884,0.5250,8.3767